const $=id=>document.getElementById(id);
const state={products:[],cart:new Map(),category:'All',query:'',manageQuery:'',staff:null,csrf:'',imageData:'',carouselIndex:0};
const money=cents=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const staticPrototype=location.hostname.endsWith('github.io');
let staticCatalog=null;

async function digest(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
async function staticApi(path,options={}){
  const method=options.method||'GET';
  const body=JSON.parse(options.body||'{}');
  if(path==='/api/auth/session')return sessionStorage.getItem('cappeto_demo_session')?{authenticated:true,user:{email:'Cappeto owner',role:'owner'},csrfToken:'static-preview'}:{authenticated:false};
  if(path==='/api/auth/login'&&method==='POST'){
    const fingerprint=await digest(`${String(body.email||'').trim().toLowerCase()}:${String(body.password||'')}`);
    if(!body.consent||fingerprint!=='b6b030b845221156f2bd566f039e0d9d076c636f019b6e6f4e0a3fedd4b5d336')throw new Error('Email or password is incorrect.');
    sessionStorage.setItem('cappeto_demo_session','active');return{user:{email:'Cappeto owner',role:'owner'},csrfToken:'static-preview'};
  }
  if(path==='/api/auth/logout'){sessionStorage.removeItem('cappeto_demo_session');return{ok:true}}
  if(!staticCatalog)staticCatalog=await fetch('data/products.json',{cache:'no-store'}).then(response=>response.json());
  if(path==='/api/products'&&method==='GET')return staticCatalog;
  if(path==='/api/products'&&method==='POST'){
    if(!sessionStorage.getItem('cappeto_demo_session'))throw new Error('Please sign in again.');
    if(staticCatalog.products.length>=20)throw new Error('The 20-product limit has been reached.');
    const product={id:`demo-${Date.now()}`,name:body.name,category:body.category,description:body.description,priceCents:Math.round(Number(body.price)*100),vatRate:Number(body.vatRate),stock:Number(body.stock),purchaseDate:body.purchaseDate,returned:0,damaged:0,sold:0,imageUrl:body.imageData};
    staticCatalog.products.push(product);return{product};
  }
  if(path.endsWith('/inventory')&&path.startsWith('/api/products/')&&method==='PATCH'){
    const id=decodeURIComponent(path.slice(14,-10));const product=staticCatalog.products.find(entry=>entry.id===id);if(!product)throw new Error('Product not found.');
    applyInventoryChange(product,body.action,Number(body.quantity));product.vatRate=Number(body.vatRate);if(body.purchaseDate)product.purchaseDate=body.purchaseDate;return{product};
  }
  if(path.startsWith('/api/products/')&&method==='DELETE'){staticCatalog.products=staticCatalog.products.filter(product=>product.id!==decodeURIComponent(path.slice(14)));return{ok:true}}
  if((path==='/api/orders/quote'||path==='/api/orders')&&method==='POST'){
    const lines=(body.items||[]).map(item=>({product:staticCatalog.products.find(entry=>entry.id===item.productId),quantity:item.quantity})).filter(line=>line.product);const subtotalCents=lines.reduce((sum,line)=>sum+line.product.priceCents*line.quantity,0);
    const vatCents=lines.reduce((sum,line)=>sum+Math.round(line.product.priceCents*line.quantity*Number(line.product.vatRate??staticCatalog.vatRate)/100),0);if(path==='/api/orders')lines.forEach(line=>applyInventoryChange(line.product,'sold',line.quantity));return{subtotalCents,vatCents,totalCents:subtotalCents+vatCents,vatRate:staticCatalog.vatRate,orderId:`DEMO-${Date.now().toString().slice(-6)}`};
  }
  throw new Error('This action is unavailable.');
}

async function api(path,options={}){
  if(staticPrototype)return staticApi(path,options);
  const response=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(state.csrf?{'X-CSRF-Token':state.csrf}:{}),...options.headers},...options});
  const body=await response.json().catch(()=>({error:'Unexpected server response'}));
  if(!response.ok) throw new Error(body.error||'Request failed');
  return body;
}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function enterApp(){ $('authView').classList.add('hidden');$('appView').classList.remove('hidden');renderAll() }
function showStaffControls(enabled){document.querySelectorAll('.staff-only').forEach(el=>el.classList.toggle('hidden',!enabled));$('sessionLabel').textContent=enabled?state.staff.email:'Customer view'}

async function loadCatalog(){const data=await api('/api/products');state.products=data.products;state.vatRate=data.vatRate;renderAll()}
function renderAll(){renderCategories();renderProducts();renderCart();renderManager();}
function renderCategories(){const categories=['All',...new Set(state.products.map(p=>p.category))];$('categoryRow').innerHTML=categories.map(name=>`<button type="button" class="category-button ${state.category===name?'active':''}" data-category="${escapeHtml(name)}">${escapeHtml(name)}</button>`).join('')}
function visibleProducts(){const query=state.query.toLowerCase();return state.products.filter(p=>(state.category==='All'||p.category===state.category)&&(`${p.name} ${p.description}`.toLowerCase().includes(query)))}
function renderProducts(){const shown=visibleProducts();$('productGrid').innerHTML=shown.length?shown.map((p,index)=>`<article class="product-card" data-slide="${index}"><div class="product-image"><img src="${escapeHtml(p.imageUrl)}" alt="${escapeHtml(p.name)}" loading="lazy"></div><div class="product-content"><div class="product-top"><h2>${escapeHtml(p.name)}</h2><span class="product-price">${money(p.priceCents)}</span></div><p class="product-description">${escapeHtml(p.description)}</p><div class="product-footer"><span class="stock">${p.stock>0?`${p.stock} available`:'Sold out'}</span><button class="add-button" type="button" data-add="${p.id}" ${p.stock<1?'disabled':''}>Add</button></div></div></article>`).join(''):'<p class="empty-state">No products match this view.</p>';state.carouselIndex=Math.min(state.carouselIndex,Math.max(0,shown.length-1));updateCarouselStatus()}
function carouselStep(){const first=$('productGrid').querySelector('.product-card');return first?first.getBoundingClientRect().width+18:0}
function visibleCarouselCards(){const step=carouselStep();return step?Math.max(1,Math.floor(($('productGrid').clientWidth+18)/step)):1}
function moveCarousel(direction){const shown=visibleProducts();if(!shown.length)return;const visible=visibleCarouselCards();state.carouselIndex=Math.max(0,Math.min(state.carouselIndex+direction,Math.max(0,shown.length-visible)));$('productGrid').scrollTo({left:state.carouselIndex*carouselStep(),behavior:'smooth'});updateCarouselStatus()}
function updateCarouselStatus(){const shown=visibleProducts();const visible=visibleCarouselCards();const last=Math.min(shown.length,state.carouselIndex+visible);$('carouselPosition').textContent=shown.length?`${state.carouselIndex+1}–${last} / ${shown.length}`:'0 / 0';$('previousProduct').disabled=state.carouselIndex===0;$('nextProduct').disabled=!shown.length||last>=shown.length}
function renderCart(){let count=0;const lines=[];for(const [id,quantity] of state.cart){const p=state.products.find(item=>item.id===id);if(!p)continue;count+=quantity;lines.push(`<div class="cart-line"><img src="${escapeHtml(p.imageUrl)}" alt=""><div><strong>${escapeHtml(p.name)}</strong><small>${money(p.priceCents)} each</small></div><div class="qty-controls"><button type="button" data-minus="${id}" aria-label="Remove one ${escapeHtml(p.name)}">−</button><b>${quantity}</b><button type="button" data-plus="${id}" aria-label="Add one ${escapeHtml(p.name)}">+</button></div></div>`)}$('cartCount').textContent=count;$('cartLines').innerHTML=lines.join('')||'<p class="empty-state">Your order is empty.</p>';calculateTotals()}
async function calculateTotals(){const items=[...state.cart].map(([productId,quantity])=>({productId,quantity}));try{const totals=items.length?await api('/api/orders/quote',{method:'POST',body:JSON.stringify({items})}):{subtotalCents:0,vatCents:0,totalCents:0,vatRate:state.vatRate||15};$('subtotal').textContent=money(totals.subtotalCents);$('vat').textContent=money(totals.vatCents);$('total').textContent=money(totals.totalCents);$('vatLabel').textContent=`VAT (${totals.vatRate}%)`;$('placeOrder').disabled=!items.length}catch(error){toast(error.message)}}
function applyInventoryChange(product,action,quantity){if(!Number.isInteger(quantity)||quantity<1||quantity>9999)throw new Error('Enter a valid whole quantity.');product.returned=Number(product.returned||0);product.damaged=Number(product.damaged||0);product.sold=Number(product.sold||0);if(action==='add'||action==='return')product.stock+=quantity;if(action==='return')product.returned+=quantity;if(action==='damage'||action==='sold'){if(quantity>product.stock)throw new Error('Quantity exceeds available inventory.');product.stock-=quantity;product[action==='damage'?'damaged':'sold']+=quantity}}
function renderManager(){const query=state.manageQuery.toLowerCase();const products=state.products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(query));$('capacityLabel').textContent=`${state.products.length} / 20`;$('productForm').querySelector('button[type=submit]').disabled=state.products.length>=20;$('manageList').innerHTML=products.map(p=>`<article class="manage-item"><img src="${escapeHtml(p.imageUrl)}" alt=""><div class="manage-summary"><div><strong>${escapeHtml(p.name)}</strong><span class="inventory-status ${p.stock<1?'sold-out':''}">${p.stock<1?'Sold Out':'In stock'}</span></div><small>${escapeHtml(p.category)} · Purchased ${escapeHtml(p.purchaseDate||'Not recorded')}</small><div class="inventory-metrics"><span>Quantity <b>${p.stock}</b></span><span>VAT <b>${Number(p.vatRate??state.vatRate)}%</b></span><span>Sold <b>${Number(p.sold||0)}</b></span><span>Returns <b>${Number(p.returned||0)}</b></span><span>Damage <b>${Number(p.damaged||0)}</b></span></div></div><strong class="item-price">${money(p.priceCents)}</strong><div class="inventory-actions"><input type="number" min="1" max="9999" step="1" value="1" aria-label="Quantity for ${escapeHtml(p.name)}" data-inventory-quantity="${p.id}"><select aria-label="Inventory action for ${escapeHtml(p.name)}" data-inventory-action="${p.id}"><option value="add">Add inventory</option><option value="return">Return</option><option value="damage">Damage</option><option value="sold">Sold</option></select><input type="number" min="0" max="100" step="0.01" value="${Number(p.vatRate??state.vatRate)}" aria-label="VAT percent for ${escapeHtml(p.name)}" data-inventory-vat="${p.id}"><input type="date" value="${escapeHtml(p.purchaseDate||'')}" aria-label="Purchase date for ${escapeHtml(p.name)}" data-inventory-date="${p.id}"><button class="button inventory-button" type="button" data-inventory-apply="${p.id}">Apply</button><button class="delete-button" type="button" data-delete="${p.id}">Delete</button></div></article>`).join('')||'<p class="empty-state">No product matches your search.</p>'}
function renderProductPreview(){const value=(id,fallback)=>$(id).value.trim()||fallback;$('previewName').textContent=value('productName','Product name');$('previewCategory').textContent=value('productCategory','Category');$('previewPrice').textContent=money(Math.round((Number($('productPrice').value)||0)*100));$('previewVat').textContent=`${Number($('productVat').value)||0}%`;$('previewStock').textContent=String(Number($('productStock').value)||0);$('previewDate').textContent=$('productPurchaseDate').value||'Not selected';$('previewDescription').textContent=value('productDescription','Short product description')}
function openCart(open){$('cartDrawer').classList.toggle('open',open);$('scrim').classList.toggle('open',open);$('cartDrawer').setAttribute('aria-hidden',String(!open))}
function switchView(view){$('catalogView').classList.toggle('hidden',view!=='catalog');$('manageView').classList.toggle('hidden',view!=='manage');document.querySelectorAll('.nav-button').forEach(button=>button.classList.toggle('active',button.dataset.view===view))}

$('authForm').addEventListener('submit',async event=>{event.preventDefault();$('authError').textContent='';try{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('staffEmail').value.trim(),password:$('authCode').value,consent:$('consent').checked})});state.staff=result.user;state.csrf=result.csrfToken;showStaffControls(true);await loadCatalog();enterApp()}catch(error){$('authError').textContent=error.message}});
$('browseButton').addEventListener('click',async()=>{showStaffControls(false);await loadCatalog();enterApp()});
$('logoutButton').addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'});location.reload()});
$('categoryRow').addEventListener('click',event=>{const button=event.target.closest('[data-category]');if(!button)return;state.category=button.dataset.category;state.carouselIndex=0;renderCategories();renderProducts()});
$('productGrid').addEventListener('click',event=>{const id=event.target.closest('[data-add]')?.dataset.add;if(!id)return;const p=state.products.find(item=>item.id===id);const quantity=Math.min((state.cart.get(id)||0)+1,p.stock);state.cart.set(id,quantity);renderCart();toast(`${p.name} added`)});
$('searchInput').addEventListener('input',event=>{state.query=event.target.value;state.carouselIndex=0;renderProducts()});
$('previousProduct').addEventListener('click',()=>moveCarousel(-1));$('nextProduct').addEventListener('click',()=>moveCarousel(1));
$('productGrid').addEventListener('keydown',event=>{if(event.key==='ArrowRight'){event.preventDefault();moveCarousel(1)}if(event.key==='ArrowLeft'){event.preventDefault();moveCarousel(-1)}});
$('productGrid').addEventListener('scroll',()=>{clearTimeout(state.carouselTimer);state.carouselTimer=setTimeout(()=>{const step=carouselStep();if(step){state.carouselIndex=Math.round($('productGrid').scrollLeft/step);updateCarouselStatus()}},80)});
window.addEventListener('resize',()=>{clearTimeout(state.resizeTimer);state.resizeTimer=setTimeout(()=>{state.carouselIndex=0;$('productGrid').scrollTo({left:0});updateCarouselStatus()},120)});
$('cartButton').addEventListener('click',()=>openCart(true));$('closeCart').addEventListener('click',()=>openCart(false));$('scrim').addEventListener('click',()=>openCart(false));
$('cartLines').addEventListener('click',event=>{const plus=event.target.closest('[data-plus]')?.dataset.plus;const minus=event.target.closest('[data-minus]')?.dataset.minus;const id=plus||minus;if(!id)return;const p=state.products.find(item=>item.id===id);const next=(state.cart.get(id)||0)+(plus?1:-1);if(next<=0)state.cart.delete(id);else state.cart.set(id,Math.min(next,p.stock));renderCart()});
document.querySelectorAll('.nav-button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
$('productImage').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{state.imageData=await toWebP(file);for(const id of ['uploadPreview','previewPicture']){$(id).style.backgroundImage=`url(${state.imageData})`;$(id).classList.add('has-image')}$('productMessage').textContent=''}catch(error){$('productMessage').textContent=error.message}});
$('productForm').addEventListener('input',renderProductPreview);
async function toWebP(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPG, PNG, or WebP image.');if(file.size>8*1024*1024)throw new Error('The source picture must be 8 MB or smaller.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/webp',.84)}
$('productForm').addEventListener('submit',async event=>{event.preventDefault();if(!state.imageData){$('productMessage').textContent='Choose a product picture first.';return}const payload={name:$('productName').value,category:$('productCategory').value,description:$('productDescription').value,price:Number($('productPrice').value),vatRate:Number($('productVat').value),stock:Number($('productStock').value),purchaseDate:$('productPurchaseDate').value,imageData:state.imageData};try{await api('/api/products',{method:'POST',body:JSON.stringify(payload)});event.target.reset();$('productVat').value='15';state.imageData='';for(const id of ['uploadPreview','previewPicture']){$(id).style.backgroundImage='';$(id).classList.remove('has-image')}renderProductPreview();$('productMessage').textContent='Product published and added to inventory.';await loadCatalog();$('manageList').scrollIntoView({behavior:'smooth',block:'start'})}catch(error){$('productMessage').textContent=error.message}});
$('manageSearch').addEventListener('input',event=>{state.manageQuery=event.target.value;renderManager()});
$('manageList').addEventListener('click',async event=>{const applyId=event.target.closest('[data-inventory-apply]')?.dataset.inventoryApply;if(applyId){const escaped=CSS.escape(applyId);const quantity=Number(document.querySelector(`[data-inventory-quantity="${escaped}"]`).value);const action=document.querySelector(`[data-inventory-action="${escaped}"]`).value;const vatRate=Number(document.querySelector(`[data-inventory-vat="${escaped}"]`).value);const purchaseDate=document.querySelector(`[data-inventory-date="${escaped}"]`).value;try{await api(`/api/products/${encodeURIComponent(applyId)}/inventory`,{method:'PATCH',body:JSON.stringify({action,quantity,vatRate,purchaseDate})});await loadCatalog();toast('Inventory updated')}catch(error){toast(error.message)}return}const id=event.target.closest('[data-delete]')?.dataset.delete;if(!id||!confirm('Delete this product from the catalog?'))return;try{await api(`/api/products/${encodeURIComponent(id)}`,{method:'DELETE'});state.cart.delete(id);await loadCatalog();toast('Product deleted')}catch(error){toast(error.message)}});
$('placeOrder').addEventListener('click',async()=>{const items=[...state.cart].map(([productId,quantity])=>({productId,quantity}));try{const result=await api('/api/orders',{method:'POST',body:JSON.stringify({items})});state.cart.clear();await loadCatalog();openCart(false);toast(`Order ${result.orderId} placed · ${money(result.totalCents)}`)}catch(error){toast(error.message)}});

api('/api/auth/session').then(async result=>{if(result.authenticated){state.staff=result.user;state.csrf=result.csrfToken;showStaffControls(true);await loadCatalog();enterApp()}}).catch(()=>{});
