const $=id=>document.getElementById(id);
const state={products:[],cart:new Map(),category:'All',query:'',staff:null,csrf:'',imageData:'',carouselIndex:0};
const money=cents=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

async function api(path,options={}){
  const response=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(state.csrf?{'X-CSRF-Token':state.csrf}:{}),...options.headers},...options});
  const body=await response.json().catch(()=>({error:'Unexpected server response'}));
  if(!response.ok) throw new Error(body.error||'Request failed');
  return body;
}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function enterApp(){ $('authView').classList.add('hidden');$('appView').classList.remove('hidden');renderAll() }
function showStaffControls(enabled){document.querySelectorAll('.staff-only').forEach(el=>el.classList.toggle('hidden',!enabled));$('sessionLabel').textContent=enabled?state.staff.email:'Customer view'}

async function loadCatalog(){const data=await api('/api/products');state.products=data.products;state.vatRate=data.vatRate;renderAll()}
function renderAll(){renderCategories();renderProducts();renderCart();renderManager();}
function renderCategories(){const categories=['All',...new Set(state.products.map(p=>p.category))];$('categoryRow').innerHTML=categories.map(name=>`<button type="button" class="category-button ${state.category===name?'active':''}" data-category="${escapeHtml(name)}">${escapeHtml(name)}</button>`).join('')}
function visibleProducts(){const query=state.query.toLowerCase();return state.products.filter(p=>(state.category==='All'||p.category===state.category)&&(`${p.name} ${p.description}`.toLowerCase().includes(query)))}
function renderProducts(){const shown=visibleProducts();$('productGrid').innerHTML=shown.length?shown.map((p,index)=>`<article class="product-card" data-slide="${index}"><div class="product-image"><img src="${escapeHtml(p.imageUrl)}" alt="${escapeHtml(p.name)}" loading="lazy"></div><div class="product-content"><div class="product-top"><h2>${escapeHtml(p.name)}</h2><span class="product-price">${money(p.priceCents)}</span></div><p class="product-description">${escapeHtml(p.description)}</p><div class="product-footer"><span class="stock">${p.stock>0?`${p.stock} available`:'Sold out'}</span><button class="add-button" type="button" data-add="${p.id}" ${p.stock<1?'disabled':''}>Add</button></div></div></article>`).join(''):'<p class="empty-state">No products match this view.</p>';state.carouselIndex=Math.min(state.carouselIndex,Math.max(0,shown.length-1));updateCarouselStatus()}
function carouselStep(){const first=$('productGrid').querySelector('.product-card');return first?first.getBoundingClientRect().width+18:0}
function moveCarousel(direction){const shown=visibleProducts();if(!shown.length)return;const visible=window.innerWidth<=760?1:window.innerWidth<=1100?2:3;state.carouselIndex=Math.max(0,Math.min(state.carouselIndex+direction,Math.max(0,shown.length-visible)));$('productGrid').scrollTo({left:state.carouselIndex*carouselStep(),behavior:'smooth'});updateCarouselStatus()}
function updateCarouselStatus(){const shown=visibleProducts();const visible=window.innerWidth<=760?1:window.innerWidth<=1100?2:3;const last=Math.min(shown.length,state.carouselIndex+visible);$('carouselPosition').textContent=shown.length?`${state.carouselIndex+1}–${last} / ${shown.length}`:'0 / 0';$('previousProduct').disabled=state.carouselIndex===0;$('nextProduct').disabled=!shown.length||last>=shown.length}
function renderCart(){let count=0;const lines=[];for(const [id,quantity] of state.cart){const p=state.products.find(item=>item.id===id);if(!p)continue;count+=quantity;lines.push(`<div class="cart-line"><img src="${escapeHtml(p.imageUrl)}" alt=""><div><strong>${escapeHtml(p.name)}</strong><small>${money(p.priceCents)} each</small></div><div class="qty-controls"><button type="button" data-minus="${id}" aria-label="Remove one ${escapeHtml(p.name)}">−</button><b>${quantity}</b><button type="button" data-plus="${id}" aria-label="Add one ${escapeHtml(p.name)}">+</button></div></div>`)}$('cartCount').textContent=count;$('cartLines').innerHTML=lines.join('')||'<p class="empty-state">Your order is empty.</p>';calculateTotals()}
async function calculateTotals(){const items=[...state.cart].map(([productId,quantity])=>({productId,quantity}));try{const totals=items.length?await api('/api/orders/quote',{method:'POST',body:JSON.stringify({items})}):{subtotalCents:0,vatCents:0,totalCents:0,vatRate:state.vatRate||15};$('subtotal').textContent=money(totals.subtotalCents);$('vat').textContent=money(totals.vatCents);$('total').textContent=money(totals.totalCents);$('vatLabel').textContent=`VAT (${totals.vatRate}%)`;$('placeOrder').disabled=!items.length}catch(error){toast(error.message)}}
function renderManager(){$('capacityLabel').textContent=`${state.products.length} / 20`;$('productForm').querySelector('button[type=submit]').disabled=state.products.length>=20;$('manageList').innerHTML=state.products.map(p=>`<div class="manage-item"><img src="${escapeHtml(p.imageUrl)}" alt=""><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.category)} · ${p.stock} available</small></div><strong class="item-price">${money(p.priceCents)}</strong><button class="delete-button" type="button" data-delete="${p.id}">Delete</button></div>`).join('')}
function openCart(open){$('cartDrawer').classList.toggle('open',open);$('scrim').classList.toggle('open',open);$('cartDrawer').setAttribute('aria-hidden',String(!open))}
function switchView(view){$('catalogView').classList.toggle('hidden',view!=='catalog');$('manageView').classList.toggle('hidden',view!=='manage');document.querySelectorAll('.nav-button').forEach(button=>button.classList.toggle('active',button.dataset.view===view))}

$('authForm').addEventListener('submit',async event=>{event.preventDefault();$('authError').textContent='';try{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('staffEmail').value.trim(),password:$('authCode').value,consent:$('consent').checked})});state.staff=result.user;state.csrf=result.csrfToken;showStaffControls(true);await loadCatalog();enterApp()}catch(error){$('authError').textContent=error.message}});
$('browseButton').addEventListener('click',async()=>{showStaffControls(false);await loadCatalog();enterApp()});
$('logoutButton').addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'});location.reload()});
$('categoryRow').addEventListener('click',event=>{const button=event.target.closest('[data-category]');if(!button)return;state.category=button.dataset.category;state.carouselIndex=0;renderCategories();renderProducts()});
$('productGrid').addEventListener('click',event=>{const id=event.target.closest('[data-add]')?.dataset.add;if(!id)return;const p=state.products.find(item=>item.id===id);const quantity=Math.min((state.cart.get(id)||0)+1,p.stock);state.cart.set(id,quantity);renderCart();toast(`${p.name} added`)});
$('searchInput').addEventListener('input',event=>{state.query=event.target.value;state.carouselIndex=0;renderProducts()});
$('previousProduct').addEventListener('click',()=>moveCarousel(-1));$('nextProduct').addEventListener('click',()=>moveCarousel(1));
$('productGrid').addEventListener('keydown',event=>{if(event.key==='ArrowRight'){event.preventDefault();moveCarousel(1)}if(event.key==='ArrowLeft'){event.preventDefault();moveCarousel(-1)}});
$('productGrid').addEventListener('scroll',()=>{clearTimeout(state.carouselTimer);state.carouselTimer=setTimeout(()=>{const step=carouselStep();if(step){state.carouselIndex=Math.round($('productGrid').scrollLeft/step);updateCarouselStatus()}},80)});
window.addEventListener('resize',()=>{clearTimeout(state.resizeTimer);state.resizeTimer=setTimeout(()=>{state.carouselIndex=0;$('productGrid').scrollTo({left:0});updateCarouselStatus()},120)});
$('cartButton').addEventListener('click',()=>openCart(true));$('closeCart').addEventListener('click',()=>openCart(false));$('scrim').addEventListener('click',()=>openCart(false));
$('cartLines').addEventListener('click',event=>{const plus=event.target.closest('[data-plus]')?.dataset.plus;const minus=event.target.closest('[data-minus]')?.dataset.minus;const id=plus||minus;if(!id)return;const p=state.products.find(item=>item.id===id);const next=(state.cart.get(id)||0)+(plus?1:-1);if(next<=0)state.cart.delete(id);else state.cart.set(id,Math.min(next,p.stock));renderCart()});
document.querySelectorAll('.nav-button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
$('productImage').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{state.imageData=await toWebP(file);$('uploadPreview').style.backgroundImage=`url(${state.imageData})`;$('uploadPreview').classList.add('has-image');$('productMessage').textContent=''}catch(error){$('productMessage').textContent=error.message}});
async function toWebP(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPG, PNG, or WebP image.');if(file.size>8*1024*1024)throw new Error('The source picture must be 8 MB or smaller.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/webp',.84)}
$('productForm').addEventListener('submit',async event=>{event.preventDefault();if(!state.imageData){$('productMessage').textContent='Choose a product picture first.';return}const payload={name:$('productName').value,category:$('productCategory').value,description:$('productDescription').value,price:Number($('productPrice').value),stock:Number($('productStock').value),imageData:state.imageData};try{await api('/api/products',{method:'POST',body:JSON.stringify(payload)});event.target.reset();state.imageData='';$('uploadPreview').style.backgroundImage='';$('uploadPreview').classList.remove('has-image');$('productMessage').textContent='Product published.';await loadCatalog()}catch(error){$('productMessage').textContent=error.message}});
$('manageList').addEventListener('click',async event=>{const id=event.target.closest('[data-delete]')?.dataset.delete;if(!id||!confirm('Delete this product from the catalog?'))return;try{await api(`/api/products/${encodeURIComponent(id)}`,{method:'DELETE'});state.cart.delete(id);await loadCatalog();toast('Product deleted')}catch(error){toast(error.message)}});
$('placeOrder').addEventListener('click',async()=>{const items=[...state.cart].map(([productId,quantity])=>({productId,quantity}));try{const result=await api('/api/orders',{method:'POST',body:JSON.stringify({items})});state.cart.clear();await loadCatalog();openCart(false);toast(`Order ${result.orderId} placed · ${money(result.totalCents)}`)}catch(error){toast(error.message)}});

api('/api/auth/session').then(async result=>{if(result.authenticated){state.staff=result.user;state.csrf=result.csrfToken;showStaffControls(true);await loadCatalog();enterApp()}}).catch(()=>{});
